### PR TITLE
Tooltip for delete should be "Delete review"

### PR DESCRIPTION
**Pull request by djoldman**

### CODE REVIEW

**Comment by EricPryzant** [comment]
Thanks for catching this mistake! I've approved this PR and will deploy the update soon

**Comment by EricPryzant** [comment]
Also, for future reference, the correct way to create a branch is to first create an issue in github, assign it to yourself, and let the branch bot create the new branch for you. This way everything stays organized for future reference.

**Review by EricPryzant — APPROVED** [review]
Good catch! Thanks for fixing this.

**Comment by djoldman** [comment]
Happy to help.  I have forked your code and made some changes to offer a similar service to your friendly UIUC MCS students:

https://github.com/uiuc-mcs/uiuc-mcs
https://uiucmcs.org/

Happy to hear your feedback!

> Also, for future reference, the correct way to create a branch is to first create an issue in github, assign it to yourself, and let the branch bot create the new branch for you. This way everything stays organized for future reference.

No problem, I will do so for future PRs.

**Pull request merged**
